### ISSUE TITLE
Luigi >= 2.8.3: AttributeError: 'str' object has no attribute 'exists'

### ISSUE THREAD

**Issue by chris-tran-16** [d6t/d6tflow#7]
I get an error if I have luigi>=2.8.4 installed.

When I reinstall luigi==2.8.3 I do not get this error when trying to run my tasks.

> Traceback (most recent call last):
  File "/home/chris/Code/cloud_storage/combined_tasks.py", line 21, in <module>
    d6tflow.show(TaskCombineData())
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tflow/__init__.py", line 165, in show
    preview(task)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tflow/__init__.py", line 53, in preview
    print(luigi.tools.deps_tree.print_tree(t))
  File "/home/chris/anaconda3/lib/python3.7/site-packages/luigi/tools/deps_tree.py", line 48, in print_tree
    is_task_complete = task.complete()
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tcollect/__init__.py", line 107, in wrapper
    raise e
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tcollect/__init__.py", line 101, in wrapper
    return func(self, *args, **kwargs)
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tflow/tasks/__init__.py", line 48, in complete
    complete = super().complete()
  File "/home/chris/anaconda3/lib/python3.7/site-packages/luigi/task.py", line 572, in complete
    return all(map(lambda output: output.exists(), outputs))
  File "/home/chris/anaconda3/lib/python3.7/site-packages/luigi/task.py", line 572, in <lambda>
    return all(map(lambda output: output.exists(), outputs))
  File "/home/chris/anaconda3/lib/python3.7/site-packages/d6tflow/targets/__init__.py", line 58, in exists
    return self.path.exists()
AttributeError: 'str' object has no attribute 'exists'

**Comment by Uendert** [comment]
Hi, I get the same error: _AttributeError: 'str' object has no attribute 'exists'_
 
When I try to run the default training classifier in the[ d6tflow-template](https://github.com/d6t/d6tflow-template), namely RandomForestClassifier, the above error shows up. Does this have to do with my luigi version?  For the recording, my version is  luigi 2.8.5.

**Comment by astenuz** [comment]
happens also when i try to run the quickstart example

**Comment by Uendert** [comment]
It seems to have something to do with luigi version. When I uninstall  luigi==2.8.5
then install luigi==2.8.3 it does work out for me.

**Comment by Upabjojr** [comment]
I believe this edit is the problem:
https://github.com/spotify/luigi/pull/2548/files#diff-5f701ca186c1533d8b4d56f3949c579aR218

**Comment by astenuz** [comment]
So is it just waiting for the update of Luigi?

**Comment by Upabjojr** [comment]
You can bypass this problem by overwriting the Target constructor in the d6tflow class inheriting from luigi's Target and avoid that path be cast to string.

**Comment by d6tdev** [comment]
Thanks for reporting! Fixed in 0.1.5 works with both luigi versions. Pls reopen if problems
